Begin `hop ignite from-compose`
hopinc/hop_cli pull request #8
Opened 2022-09-21 20:10 UTC by alii

I am learning rust

2022-09-21 20:45 UTC, pxseu commented on src/main.rs
> -use hop_cli::commands::Commands;
what are these two line removes for?

2022-09-21 20:46 UTC, alii commented on src/main.rs
> -use hop_cli::commands::Commands;
didnt like it

2022-09-21 21:12 UTC, pxseu commented on src/main.rs
> -use hop_cli::commands::Commands;
kk

2022-09-23 23:58 UTC, pxseu requested changes

2022-09-23 23:58 UTC, pxseu commented on src/commands/ignite/from_compose.rs
> +            )));
this too

2022-09-23 23:58 UTC, pxseu commented on Cargo.toml
> +serde_derive = "1.0.144"
remove this dep since derive is part of serde now

2022-09-23 23:59 UTC, pxseu commented on src/commands/ignite/from_compose.rs
> +        )));
replace for anyhow macro

2022-09-24 00:09 UTC, pxseu submitted a review, later dismissed
LGTM ALI🔥

2022-11-27 20:28 UTC, pxseu approved these changes

2022-11-27 20:29 UTC, merged